#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Endereco.Resource", IsApplication=true)]

namespace Endereco
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Critical = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Entrar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FundoAcesso = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MConsulta = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int MExit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MNovo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int MUser = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int UserAdd = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int btAcessoCadastar = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int btAcessoEntrar = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int btPrincipalCadEndereco = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int btPrincipalConsEndereco = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int btPrincipalConsUsuario = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int btPrincipalSair = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int etAcessoSenha = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int etAcessoUsuario = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int etUsuarioID = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int etUsuarioNome = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int lbAcessoSenha = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int lbAcessoUsuario = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int lblUsuarioID = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int lblUsuarioNome = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout3 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout4 = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int lvUsuarioExibir = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int tvPrincipalUsuario = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Acesso = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Principal = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Usuario = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
